if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "The optional pinned UMD/ttsim integration is validated on Linux only")
endif()
set(TT_UMD_SOURCE_DIR "${CMAKE_SOURCE_DIR}/third_party/tt-umd" CACHE PATH "Pinned TT-UMD source checkout")
find_package(Git REQUIRED)
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${TT_UMD_SOURCE_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE umd_commit OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE umd_pin_status)
if(NOT umd_pin_status EQUAL 0 OR NOT umd_commit STREQUAL "1a513b2ca8a8955db1fe306b6d65dee2ffe5c9bc")
    message(FATAL_ERROR "Run scripts/fetch_upstream.py; TT-UMD must match the provenance pin")
endif()
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${TT_UMD_SOURCE_DIR}" status --porcelain
    OUTPUT_VARIABLE umd_dirty OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE umd_dirty_status)
if(NOT umd_dirty_status EQUAL 0 OR NOT umd_dirty STREQUAL "")
    message(FATAL_ERROR "Pinned TT-UMD checkout has source modifications")
endif()
set(TT_UMD_BUILD_ALL OFF CACHE BOOL "" FORCE)
set(TT_UMD_BUILD_SIMULATION ON CACHE BOOL "" FORCE)
foreach(feature TESTS PYTHON TOOLS EXAMPLES RDMA JTAG EMULE)
    set(TT_UMD_BUILD_${feature} OFF CACHE BOOL "" FORCE)
endforeach()
set(TT_UMD_ENABLE_TRACY OFF CACHE BOOL "" FORCE)
set(TT_UMD_ENABLE_CLANG_TIDY OFF CACHE BOOL "" FORCE)
add_subdirectory("${TT_UMD_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/umd" EXCLUDE_FROM_ALL)

add_library(tt_transfer_umd src/umd_backend.cpp)
target_include_directories(tt_transfer_umd PUBLIC include)
target_compile_features(tt_transfer_umd PUBLIC cxx_std_20)
target_link_libraries(tt_transfer_umd PUBLIC tt_transfer PRIVATE umd::tt-umd)

add_executable(umd_demo examples/umd_demo.cpp)
target_compile_features(umd_demo PRIVATE cxx_std_20)
target_link_libraries(umd_demo PRIVATE tt_transfer_umd)

add_executable(allocator_examples examples/allocator_examples.cpp)
target_compile_features(allocator_examples PRIVATE cxx_std_20)
target_link_libraries(allocator_examples PRIVATE umd::tt-umd)
add_test(NAME allocator_examples COMMAND allocator_examples)
